In [2]:
import yfinance as yf
import pandas as pd

In [24]:
ticker = yf.Ticker("TSLA")
hist = ticker.history(period="5y", interval="1d")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-05-11 00:00:00-04:00,52.700668,54.933334,52.333332,54.085999,247794000,0.0,0.0
2020-05-12 00:00:00-04:00,55.133331,56.219334,53.866669,53.960667,238603500,0.0,0.0
2020-05-13 00:00:00-04:00,54.722000,55.066666,50.886665,52.730667,285982500,0.0,0.0
2020-05-14 00:00:00-04:00,52.000000,53.557335,50.933334,53.555332,205233000,0.0,0.0
2020-05-15 00:00:00-04:00,52.689999,53.669998,52.436668,53.278000,157776000,0.0,0.0
...,...,...,...,...,...,...,...
2025-05-02 00:00:00-04:00,284.899994,294.779999,279.809998,287.209991,114454700,0.0,0.0
2025-05-05 00:00:00-04:00,284.570007,284.850006,274.399994,280.260010,94618900,0.0,0.0
2025-05-06 00:00:00-04:00,273.109985,277.730011,271.350006,275.350006,76715800,0.0,0.0
2025-05-07 00:00:00-04:00,276.880005,277.920013,271.000000,276.220001,71882400,0.0,0.0
2025-05-08 00:00:00-04:00,279.630005,289.799988,279.410004,284.820007,96444541,0.0,0.0

In [15]:
AAPL_hist = pd.DataFrame(hist)

In [16]:
AAPL_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-05-11 00:00:00-04:00,52.700668,54.933334,52.333332,54.085999,247794000,0.0,0.0
2020-05-12 00:00:00-04:00,55.133331,56.219334,53.866669,53.960667,238603500,0.0,0.0
2020-05-13 00:00:00-04:00,54.722000,55.066666,50.886665,52.730667,285982500,0.0,0.0
2020-05-14 00:00:00-04:00,52.000000,53.557335,50.933334,53.555332,205233000,0.0,0.0
2020-05-15 00:00:00-04:00,52.689999,53.669998,52.436668,53.278000,157776000,0.0,0.0
...,...,...,...,...,...,...,...
2025-05-02 00:00:00-04:00,284.899994,294.779999,279.809998,287.209991,114454700,0.0,0.0
2025-05-05 00:00:00-04:00,284.570007,284.850006,274.399994,280.260010,94618900,0.0,0.0
2025-05-06 00:00:00-04:00,273.109985,277.730011,271.350006,275.350006,76715800,0.0,0.0
2025-05-07 00:00:00-04:00,276.880005,277.920013,271.000000,276.220001,71882400,0.0,0.0
2025-05-08 00:00:00-04:00,279.630005,289.799988,279.410004,284.820007,96444541,0.0,0.0

In [17]:
recommendations = ticker.recommendations
major_holders = ticker.major_holders
institutional_holders = ticker.institutional_holders
mutualfund_holders = ticker.mutualfund_holders
info = ticker.info  # fundamental company data

In [18]:
recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          7   16    14     9           2
1    -1m          7   16    14     9           2
2    -2m          7   16    14     9           2
3    -3m          7   14    15     9           3

In [13]:
get_recs = ticker.get_recommendations
ticker.get_recommendations_summary

In [27]:
hist = ticker.history(period="5y", interval="1d")

In [28]:
import pandas_ta as ta
hist["RSI"] = ta.rsi(hist["Close"], length=14)
hist["MACD"] = ta.macd(hist["Close"]).iloc[:, 0]
hist["SMA_20"] = hist["Close"].rolling(20).mean()

In [29]:
hist['future_return'] = (hist['Close'].shift(-7) - hist['Close']) / hist['Close']
hist['label'] = (hist['future_return'] > 0.05).astype(int)

In [36]:
clean_hist = hist.dropna()
clean_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits,RSI,MACD,SMA_20,future_return,label
Date,,,,,,,,,,,,
2020-06-16 00:00:00-04:00,67.456665,67.525330,64.159332,65.475334,210766500,0.0,0.0,64.407452,4.468634,59.191367,0.003920,0
2020-06-17 00:00:00-04:00,65.847336,67.000000,65.504669,66.119331,148362000,0.0,0.0,65.454204,4.435966,59.803967,-0.032315,0
2020-06-18 00:00:00-04:00,66.866669,67.946671,66.297997,66.930664,146278500,0.0,0.0,66.779729,4.424541,60.431967,0.005369,0
2020-06-19 00:00:00-04:00,67.518669,67.731331,66.089333,66.726669,130195500,0.0,0.0,66.093051,4.348894,61.009633,0.078839,1
2020-06-22 00:00:00-04:00,66.663330,67.258667,66.001335,66.288002,95436000,0.0,0.0,64.555800,4.205073,61.601100,0.126026,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-23 00:00:00-04:00,254.860001,259.450012,244.429993,250.740005,150381900,0.0,0.0,48.146474,-9.123695,253.174000,0.145449,1
2025-04-24 00:00:00-04:00,250.500000,259.540009,249.199997,259.510010,94464200,0.0,0.0,50.982335,-7.402182,252.546500,0.079958,1
2025-04-25 00:00:00-04:00,261.690002,286.850006,259.630005,284.950012,167560700,0.0,0.0,58.134886,-3.939662,253.137501,-0.033690,0
2025-04-28 00:00:00-04:00,288.980011,294.859985,272.420013,285.880005,151731800,0.0,0.0,58.374009,-1.107777,254.254002,-0.033790,0
2025-04-29 00:00:00-04:00,285.500000,293.320007,279.470001,292.029999,108906600,0.0,0.0,60.001041,1.614158,255.897501,-0.024689,0

In [37]:
recs = ticker.recommendations
recs['score'] = recs['To Grade'].map({'Buy': 1, 'Hold': 0, 'Sell': -1}).fillna(0)
recs_agg = recs.resample('D').mean().rolling(7).mean()
clean_hist = clean_hist.merge(recs_agg[['score']], left_index=True, right_index=True, how='left')

KeyError: 'To Grade'

In [34]:
hist.head(50)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,RSI,MACD,SMA_20,future_return,label
Date,,,,,,,,,,,,
2020-05-11 00:00:00-04:00,52.700668,54.933334,52.333332,54.085999,247794000,0.0,0.0,NaN,NaN,NaN,0.005263,0
2020-05-12 00:00:00-04:00,55.133331,56.219334,53.866669,53.960667,238603500,0.0,0.0,NaN,NaN,NaN,0.022473,0
2020-05-13 00:00:00-04:00,54.722000,55.066666,50.886665,52.730667,285982500,0.0,0.0,NaN,NaN,NaN,0.032770,0
2020-05-14 00:00:00-04:00,52.000000,53.557335,50.933334,53.555332,205233000,0.0,0.0,NaN,NaN,NaN,0.019344,0
2020-05-15 00:00:00-04:00,52.689999,53.669998,52.436668,53.278000,157776000,0.0,0.0,NaN,NaN,NaN,0.026352,0
2020-05-18 00:00:00-04:00,55.185333,55.647999,53.591999,54.242001,174987000,0.0,0.0,NaN,NaN,NaN,-0.009611,0
2020-05-19 00:00:00-04:00,54.344666,54.804668,53.738667,53.867332,144547500,0.0,0.0,NaN,NaN,NaN,0.033403,0
2020-05-20 00:00:00-04:00,54.700001,55.066666,54.119999,54.370667,109639500,0.0,0.0,NaN,NaN,NaN,0.101207,1
2020-05-21 00:00:00-04:00,54.400002,55.500000,53.066666,55.173332,183819000,0.0,0.0,NaN,NaN,NaN,0.065201,1
2020-05-22 00:00:00-04:00,54.811333,55.452000,54.133331,54.458668,149812500,0.0,0.0,NaN,NaN,NaN,0.080893,1
2020-05-26 00:00:00-04:00,55.633331,55.639999,54.380669,54.591331,121345500,0.0,0.0,NaN,NaN,NaN,0.055577,1
2020-05-27 00:00:00-04:00,54.723999,55.180668,52.333332,54.681999,173242500,0.0,0.0,NaN,NaN,NaN,0.079770,1
2020-05-28 00:00:00-04:00,54.234001,54.983334,53.445999,53.720669,108834000,0.0,0.0,NaN,NaN,NaN,0.178839,1
2020-05-29 00:00:00-04:00,53.916668,55.666668,53.613998,55.666668,176467500,0.0,0.0,NaN,NaN,NaN,0.126551,1
2020-06-01 00:00:00-04:00,57.200001,59.933334,56.939999,59.873333,224092500,0.0,0.0,78.013516,NaN,NaN,0.141354,1
2020-06-02 00:00:00-04:00,59.646667,60.577332,58.066666,58.770668,203484000,0.0,0.0,69.786990,NaN,NaN,0.103544,1
2020-06-03 00:00:00-04:00,59.208000,59.862667,58.673332,58.863998,119242500,0.0,0.0,70.074630,NaN,NaN,0.059255,1
2020-06-04 00:00:00-04:00,59.325333,59.716667,57.229332,57.625332,133315500,0.0,0.0,61.681443,NaN,NaN,0.146371,1
2020-06-05 00:00:00-04:00,58.522667,59.101334,57.746666,59.043999,117178500,0.0,0.0,66.613694,NaN,NaN,0.108924,1
2020-06-08 00:00:00-04:00,61.266666,63.333332,60.610668,63.327999,212620500,0.0,0.0,76.465163,NaN,55.794433,0.044077,0
2020-06-09 00:00:00-04:00,62.667332,63.629333,61.595333,62.711334,170823000,0.0,0.0,73.120472,NaN,56.225700,0.067282,1
2020-06-10 00:00:00-04:00,66.125336,68.498665,65.500000,68.336670,278451000,0.0,0.0,81.199325,NaN,56.944500,-0.023560,0
2020-06-11 00:00:00-04:00,66.013336,67.930664,64.800003,64.856003,238747500,0.0,0.0,67.650599,NaN,57.550767,0.022080,0
2020-06-12 00:00:00-04:00,65.333336,65.865334,60.840000,62.352001,251451000,0.0,0.0,59.906407,NaN,57.990600,0.071102,1
2020-06-15 00:00:00-04:00,61.186001,66.589333,60.566666,66.059998,235458000,0.0,0.0,66.095791,NaN,58.629700,-0.030326,0
2020-06-16 00:00:00-04:00,67.456665,67.525330,64.159332,65.475334,210766500,0.0,0.0,64.407452,4.468634,59.191367,0.003920,0
2020-06-17 00:00:00-04:00,65.847336,67.000000,65.504669,66.119331,148362000,0.0,0.0,65.454204,4.435966,59.803967,-0.032315,0
2020-06-18 00:00:00-04:00,66.866669,67.946671,66.297997,66.930664,146278500,0.0,0.0,66.779729,4.424541,60.431967,0.005369,0
2020-06-19 00:00:00-04:00,67.518669,67.731331,66.089333,66.726669,130195500,0.0,0.0,66.093051,4.348894,61.009633,0.078839,1
2020-06-22 00:00:00-04:00,66.663330,67.258667,66.001335,66.288002,95436000,0.0,0.0,64.555800,4.205073,61.601100,0.126026,1
2020-06-23 00:00:00-04:00,66.592003,67.466667,66.267334,66.785332,95479500,0.0,0.0,65.534539,4.084145,62.210800,0.206512,1
2020-06-24 00:00:00-04:00,66.274002,66.725334,63.542667,64.056664,164394000,0.0,0.0,56.341829,3.725186,62.679533,0.427465,1
2020-06-25 00:00:00-04:00,63.618000,65.732002,62.476665,65.732002,138817500,0.0,0.0,60.047398,3.535144,63.280100,0.409623,1
2020-06-26 00:00:00-04:00,66.318665,66.333336,63.658001,63.982666,132823500,0.0,0.0,54.815623,3.206416,63.695900,0.423177,1
2020-06-29 00:00:00-04:00,64.600670,67.333336,63.234669,67.290001,135396000,0.0,0.0,61.623475,3.176157,64.066733,0.381364,1
2020-06-30 00:00:00-04:00,67.099998,72.512665,66.915337,71.987335,253777500,0.0,0.0,68.811026,3.490971,64.727567,0.430483,1
2020-07-01 00:00:00-04:00,72.199997,75.688667,72.033333,74.641998,199903500,0.0,0.0,72.002406,3.909606,65.516467,0.337102,1
2020-07-02 00:00:00-04:00,81.431999,81.866669,79.040001,80.577332,258751500,0.0,0.0,77.536794,4.666515,66.664067,0.254944,1
2020-07-06 00:00:00-04:00,85.112663,91.852669,84.402664,91.438667,308548500,0.0,0.0,83.834276,6.072787,68.283800,0.127174,1
2020-07-07 00:00:00-04:00,93.667336,95.300003,89.113998,92.657333,322345500,0.0,0.0,84.363949,7.202577,69.750267,0.079706,1
2020-07-08 00:00:00-04:00,93.666664,94.484001,87.422668,91.058670,244669500,0.0,0.0,80.631656,7.878131,71.167634,0.098808,1
2020-07-09 00:00:00-04:00,93.132668,93.903999,90.085335,92.952003,175764000,0.0,0.0,81.666148,8.468667,72.398400,0.178386,1
2020-07-10 00:00:00-04:00,93.066666,103.261330,91.734001,102.976669,350064000,0.0,0.0,85.946254,9.634517,74.304434,0.015350,0
2020-07-13 00:00:00-04:00,110.599998,119.666000,98.073997,99.804001,584781000,0.0,0.0,79.611685,10.185047,76.177034,0.063638,1
2020-07-14 00:00:00-04:00,103.733330,106.000000,95.400002,101.120003,351271500,0.0,0.0,80.261545,10.605285,77.930034,-0.002459,0
2020-07-15 00:00:00-04:00,102.866669,103.333336,97.133331,103.067329,245517000,0.0,0.0,81.215661,10.969016,79.809634,-0.083447,0
2020-07-16 00:00:00-04:00,98.477333,102.113998,97.733330,100.042664,214512000,0.0,0.0,75.140142,10.887703,81.505800,0.025962,0
2020-07-17 00:00:00-04:00,100.896667,102.500664,99.333336,100.056000,139950000,0.0,0.0,75.148969,10.700984,83.162067,-0.016224,0
2020-07-20 00:00:00-04:00,101.267334,110.000000,99.199997,109.533333,256821000,0.0,0.0,80.459166,11.188772,85.302400,-0.087578,0
2020-07-21 00:00:00-04:00,109.328667,111.666664,103.866669,104.557335,241608000,0.0,0.0,71.785875,11.046489,87.215867,-0.051563,0

In [35]:
clean_hist = hist.dropna()
clean_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits,RSI,MACD,SMA_20,future_return,label
Date,,,,,,,,,,,,
2020-06-16 00:00:00-04:00,67.456665,67.525330,64.159332,65.475334,210766500,0.0,0.0,64.407452,4.468634,59.191367,0.003920,0
2020-06-17 00:00:00-04:00,65.847336,67.000000,65.504669,66.119331,148362000,0.0,0.0,65.454204,4.435966,59.803967,-0.032315,0
2020-06-18 00:00:00-04:00,66.866669,67.946671,66.297997,66.930664,146278500,0.0,0.0,66.779729,4.424541,60.431967,0.005369,0
2020-06-19 00:00:00-04:00,67.518669,67.731331,66.089333,66.726669,130195500,0.0,0.0,66.093051,4.348894,61.009633,0.078839,1
2020-06-22 00:00:00-04:00,66.663330,67.258667,66.001335,66.288002,95436000,0.0,0.0,64.555800,4.205073,61.601100,0.126026,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-23 00:00:00-04:00,254.860001,259.450012,244.429993,250.740005,150381900,0.0,0.0,48.146474,-9.123695,253.174000,0.145449,1
2025-04-24 00:00:00-04:00,250.500000,259.540009,249.199997,259.510010,94464200,0.0,0.0,50.982335,-7.402182,252.546500,0.079958,1
2025-04-25 00:00:00-04:00,261.690002,286.850006,259.630005,284.950012,167560700,0.0,0.0,58.134886,-3.939662,253.137501,-0.033690,0
2025-04-28 00:00:00-04:00,288.980011,294.859985,272.420013,285.880005,151731800,0.0,0.0,58.374009,-1.107777,254.254002,-0.033790,0
2025-04-29 00:00:00-04:00,285.500000,293.320007,279.470001,292.029999,108906600,0.0,0.0,60.001041,1.614158,255.897501,-0.024689,0